# Generated by Django 4.0.3 on 2022-04-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review_delete_moim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='conten',
            new_name='content',
        ),
    ]
